### ISSUE TITLE
bug in `tfidf.py` 

### ISSUE THREAD

**Issue by MASHOD0** [MASHOD0/ProjectSearch#2]
the error message
```
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 24, in main
    file_idfs = tfidf.compute_idfs(file_words)
  File "C:\Users\mashh\Documents\git\ProjectSearch\src\process\tfidf.py", line 22, in compute_idfs
    for word in set(documents[doc]):
TypeError: 'NoneType' object is not iterable
```

**Comment by MASHOD0** [comment]
Problem solved !
